---

- name: Clean working directory
  file:
    state: absent
    path: "{{ working_directory }}"
  become: no
  tags: [ devstack ]

- name: Create working directory
  file:
    state: directory
    path: "{{ working_directory }}"
  become: no
  tags: [ devstack ]

- name: Copy SSH config
  blockinfile:
    path: "{{ ssh_keys_dir }}/config"
    create: yes
    block: |
      host github.com
       HostName github.com
       User git
       ForwardAgent yes
       StrictHostKeyChecking no
  become: no
  tags: [ devstack ]

- name: Clone Github repository
  git:
    repo: "{{ git_repo_url }}"
    version: "{{ git_repo_branch }}"
    dest: "{{ devstack_directory }}"
    accept_hostkey: yes
  become: no
  tags: [ devstack ]

- name: Move devstack files to {{ user }} home
  shell: ". /etc/profile && mv $DEVSTACK_USER/* /home/{{ user }}"
  tags: [ never, devstack ]
  ignore_errors: yes

- name: Install requirements
  pip:
    requirements: "{{ working_directory }}/devstack/requirements/base.txt"
    virtualenv: "{{ working_directory }}/env"
    virtualenv_python: python3
  become: no
  tags: [ devstack, env ]

- name: Change '{{ working_directory }}' owner
  file:
    path: "{{ working_directory }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: [ never, devstack ]

- name: Store current devstack user
  blockinfile:
    path: "/etc/profile"
    block: "export DEVSTACK_USER={{ user_home }}"
  tags: [ server, reconfiguration ]

- name: Configure .profile file
  blockinfile:
    path: "{{ home_dir }}/.profile"
    block: |
      export DEVSTACK_WORKSPACE={{ working_directory }}
      export VIRTUAL_ENV={{ virtual_env_dir }}
      export OPENEDX_RELEASE={{ openedx_release }}

      source {{ virtual_env_dir }}/bin/activate
      cd $DEVSTACK_WORKSPACE
    marker: "# {mark} SULTAN MANAGED BLOCK"
  tags: [ server, reconfiguration ]

- name: Install edxapp extra requirements
  git:
    repo: "{{ repo }}"
    version: "{{ version }}"
    dest: "{{ extra_requirements_directory }}/{{ package_name }}"
    accept_hostkey: yes
    key_file: yes
  loop: "{{ extra_requirements.split(',') }}"
  vars:
    repo: "{{ item.split('==').0 }}"
    package_name: "{{ repo | basename | regex_replace('^(.*).git$', '\\1') }}"
    version: "{{ item.split('==').1 | default('HEAD') }}"
  when: extra_requirements
  become: no
  tags: [ devstack, reconfiguration, env ]

- name: Checkout Github branch
  git:
    repo: "{{ git_repo_url }}"
    version: "{{ git_repo_branch }}"
    dest: "{{ devstack_directory }}"
    accept_hostkey: yes
  become: no
  # Most of the time developers don't need this behavior. However, it's
  # necessary for Sultan CI jobs.
  when: ci_build == "true"
  tags: [ never, devstack ]

