# Cloud Build testing setup
#
# This provides a simple method for very rough automated testing
# of a sultan/devstack setup using Google Cloud Build.
#
# Using it requires a few things to be set up:
#  * Cloud Build API enabled for your project
#  * Two secrets in Secret Manager:
#     * `devstack-service-key` - should contain the JSON service
#        account credentials
#     * `cloudbuild-ssh-key` - an ed25519 SSH private key. The
#        matching public key for it should be added to the GCE
#        metadata for the project (so it can ssh to instances)
#  * The cloudbuild service agent needs decrypt/read access to those
#    secrets
#
# With those, you can then make your own config (use
# `cloudbuild/configs.juniper` as a start. You will need to change at
# least `PROJECT_ID`). If you named the config `configs.myconfig`,
# you would then run `gcloud builds submit --substituations=_CONFIG=myconfig`

steps:
# using the cloud-sdk image because it already has
# gcloud installed and configured for the cloudbuild
# service user as well as a usable python environment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export CONFIG=${_CONFIG}
        export PROJECT_ID=${PROJECT_ID}
        export IMAGE=${_IMAGE}
        './cloudbuild/build.sh'
    timeout: 3600s
    
timeout: 3600s
substitutions:
  _CONFIG: "juniper"
  _IMAGE: "devstack-juniper"
