---

- name: Clean working directory
  file:
    state: absent
    path: "{{ working_directory }}"
  tags: [ devstack ]

- name: Create working directory
  file:
    state: directory
    path: "{{ working_directory }}"
  become: no
  tags: [ devstack ]

- name: Copy SSH config
  blockinfile:
    path: "{{ ssh_keys_dir }}/config"
    create: yes
    block: |
      host github.com
       HostName github.com
       User git
       ForwardAgent yes
       StrictHostKeyChecking no
  become: no
  tags: [ devstack ]

- name: Clone Github repository
  git:
    repo: "{{ git_repo_url }}"
    version: "{{ git_repo_branch }}"
    dest: "{{ devstack_directory }}"
    accept_hostkey: yes
  become: false
  tags: [ devstack ]

- name: Create devstack virtualenv
  command:
    cmd: virtualenv {{ virtual_env_dir }} -p python3
    creates: "{{ working_directory }}/env"
  become: false
  tags: [ devstack ]

- name: Move devstack files to {{ user }} home
  shell: ". /etc/profile && mv $DEVSTACK_USER/* /home/{{ user }}"
  tags: [ never, devstack ]
  ignore_errors: yes

- name: Change '{{ working_directory }}' owner
  file:
    path: "{{ working_directory }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: [ never, devstack ]

- name: Store current devstack user
  blockinfile:
    path: "/etc/profile"
    block: "export DEVSTACK_USER={{ user_home }}"
  tags: [ server, reconfiguration ]
