---

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: [ server ]

- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes
  tags: [ server ]

- name: Uninstall old versions
  apt:
    name: "{{ item }}"
    state: absent
  loop: [
    "docker",
    "docker-engine",
    "docker.io",
    "containerd",
    "runc"
  ]
  tags: [ server ]

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    force_apt_get: yes
  loop: [
    "apt-transport-https",
    "build-essential",
    "ca-certificates",
    "curl",
    "gnupg-agent",
    "software-properties-common",
    "python-pexpect",
    "python-pip",
    "python3-pip",
    "virtualenv",
    "python-setuptools"
  ]
  tags: [ server ]

- name: Install pexpect
  pip:
    name: pexpect
  become: yes
  tags: [ server ]

- name: Set inotify watchers
  sysctl:
    name=fs.inotify.max_user_watches
    value=524288
    state=present
    reload=yes
  tags: [ server ]
