---

- name: Create '{{ docker_group_name }}' group
  group:
    name: "{{ docker_group_name }}"
    state: present
  tags: [ docker ]

- name: Add '{{ user }}' to '{{ docker_group_name }}' group
  user:
    name: "{{ user }}"
    groups: "{{ docker_group_name }}"
    append: true
  tags: [ docker, reconfiguration ]

- name: Add GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: [ docker ]

- name: Add Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags: [ docker ]

- name: Install packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  loop: [
    "docker-ce",
    "docker-ce-cli",
    "containerd.io",
  ]
  tags: [ docker ]

- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false
  tags: [ docker, reconfiguration ]

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout
  tags: [ docker, reconfiguration ]

- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755
  tags: [ docker, reconfiguration ]
