---

- hosts: all
  tasks:
    - name: Add mappings to /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {{ IP_ADDRESS }} {{ item }}
        marker: "# {mark} SULTAN MANAGED BLOCK {{ item }}"
      become: yes
      with_items: "{{ EDX_HOST_NAMES.split(',') }}"
      tags: [ hosts_update ]

    - name: Remove SSH configurations
      blockinfile:
        create: yes
        path: ~/.ssh/config
        marker: "# {mark} SULTAN MANAGED HOST"
        block: ""
      become: yes
      tags: [ hosts_revert ]

    - name: Remove mappings from /etc/hosts
      blockinfile:
        path: /etc/hosts
        marker: "# {mark} SULTAN MANAGED BLOCK {{ item }}"
        content: ""
      become: yes
      with_items: "{{ EDX_HOST_NAMES.split(',') }}"
      tags: [ hosts_revert ]

    - name: Configure SSH agent forwarding
      blockinfile:
        path: ~/.ssh/config
        marker: "# {mark} SULTAN MANAGED HOST"
        create: yes
        block: |
          Host devstack
            HostName {{ IP_ADDRESS }}
            User {{ USER }}
            IdentityFile {{ SSH_KEY }}
            ForwardAgent yes
      tags: [ ssh_config ]

    - name: Get the remote instance host key
      shell: ssh-keyscan -t rsa {{ IP_ADDRESS }}
      register: host_key
      until: host_key.stdout.find(IP_ADDRESS) != -1
      retries: 10
      delay: 10
      ignore_errors: no
      tags: [ ssh_config ]

    - name: Configure SSH known hosts
      blockinfile:
        path: ~/.ssh/known_hosts
        create: yes
        block: "{{ host_key.stdout }}"
      tags: [ ssh_config ]

    - name: Ensures {{ inventory_configs_dir }} dir exists
      file:
        path: "{{ inventory_configs_dir }}"
        state: directory
      tags: [ inventory ]

    - name: Configure inventory variables
      template:
        src: dynamic-inventory/inventory.compute.gcp.yml.j2
        dest: "{{ inventory_target }}"
        mode: '0644'
      tags: [ inventory ]
